defaults:
    - default:
        title: 早晚自测体温是否正常
        value: 正常
#多个额外选项配置
#    - default:
#        #表单项标题
#        title: 体温
#        #表单项默认值
#        value: 正常
#        #表单项其他值
#        other: 其他
