defaults:
    - default:
          title: 健康状况
          value: 健康，7日内进行过核酸检测
    - default:
          title: 14天内是否有中高风险地区所在城市旅居史（如有，请选择其它，并具体填写何时旅居过何中高风险地区所在城市，参考格式：7月25日，到南京市访友，逗留2小时）
          value: 否
    - default:
          title: 14天内是否有中高风险地区旅居史（如有，请选择其它，并具体填写何时旅居过何中高风险地区，参考格式：7月25日，到南京江宁区**街道**小区办事，逗留10分钟）
          value: 否
    - default:
          title: 是否与确诊病例、无症状感染者乘坐同次航班或列车（如有，请选择其它，并填写具体车次、航班号及时间，参考格式：G1201，8月2日）
          value: 否
    - default:
          title: 隔离情况
          value: 未隔离
#多个额外选项配置
#    - default:
#        #表单项标题
#        title: 体温
#        #表单项默认值
#        value: 正常
#        #表单项其他值
#        other: 其他
