sign:
  - title: 健康状况
    value: 健康，7日内进行过核酸检测
  - title: 14天内是否有中高风险地区所在城市旅居史（如有，请选择其它，并具体填写何时旅居过何中高风险地区所在城市，参考格式：7月25日，到南京市访友，逗留2小时）
    value: 否
  - title: 14天内是否有中高风险地区旅居史（如有，请选择其它，并具体填写何时旅居过何中高风险地区，参考格式：7月25日，到南京江宁区**街道**小区办事，逗留10分钟）
    value: 否
  - title: 是否与确诊病例、无症状感染者乘坐同次航班或列车（如有，请选择其它，并填写具体车次、航班号及时间，参考格式：G1201，8月2日）
    value: 否
  - title: 隔离情况
    value: 未隔离
collector:
  name: 黑龙江大学学生疫情防控每日健康打卡（在校生）
  content:
    - title: 当前状态
      value: 在校
    - title: 在校学生体温状况
      value: 正常
    - title: 在校学生隔离情况
      value: 未隔离
    - title: 7天内是否有中高风险地区旅居史
      value: 否
    - title: 7天内是否有中高风险地区所在区（县）旅居史
      value: 否
    - title: 7天内是否有涉疫城市旅居史
      value: 否
    - title: 在校学生安全承诺
      value: 本人承诺当日按时归寝，遵守学校防疫规定，并做到未经审批不私自离校，如有特殊情况主动向辅导员老师报备
